// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace VariableCreator
{
    internal sealed partial class Vsix
    {
        public const string Id = "VariableCreator.9d282169-fb77-4072-a032-5625d47bf520";
        public const string Name = "VariableCreator";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Alberto Monteiro";
        public const string Tags = "";
    }
}
